"""
Runbook Generator Tool
Describe an incident or task → get a professional runbook.
"""


def build_runbook_prompt(incident: str) -> str:
    return f"""You are a senior DevOps/SRE engineer writing a professional runbook.

Incident or task description:
{incident}

Generate a complete runbook in this format:

# 📖 Runbook: [Give it a clear title]

## Overview
Brief description of what this runbook covers and when to use it.

## Prerequisites
- Required access/permissions
- Tools that must be installed
- Environment variables or configs needed

## Impact Assessment
- Who/what is affected
- Estimated severity
- SLA implications

## Step-by-Step Resolution

### Step 1: [Action]
```bash
# Commands if applicable
```
✅ Expected outcome:
⚠️ If this fails:

### Step 2: [Action]
```bash
# Commands if applicable
```
✅ Expected outcome:
⚠️ If this fails:

[Continue for all steps...]

## Verification
How to confirm the issue is fully resolved.

## Rollback Plan
Steps to undo changes if something goes wrong.

## Post-Incident Actions
- Monitoring to add
- Alerts to configure
- Documentation to update
- Post-mortem to schedule (if severity warrants it)

## Escalation
When and who to escalate to if this runbook doesn't resolve the issue.

---
*Runbook generated by DevOps AI Agent · Review before use in production*"""


def build_runbook_title(incident: str) -> str:
    """Extract a short title from the incident description."""
    words = incident.strip().split()
    return " ".join(words[:8]) + ("…" if len(words) > 8 else "")
